### PR TITLE
tls_available option

### PR DESCRIPTION
**Pull request by biot2**
1. Added `tls_available` parameter understanding of `INFO` structure.
2. Fixed wrongful security option check causing incorrect error code `NATS_SECURE_CONNECTION_WANTED`

### CODE REVIEW

**Comment by biot2** [comment]
I'm new to nats.c library, but it seems failed test has nothing to do with this pull request. Am I right? Should I do anything now?

**Comment by vahid-nasehi** [comment]
@kozlovic

**Comment by biot2** [comment]
@kozlovic

**Review by kozlovic — APPROVED** [review]
LGTM. It would have been nice to add the test that showed the failure to connect prior to the fix and verify that it passes now. But we can add that later. Thank you for your contribution.

**Comment by biot2** [comment]
> LGTM. It would have been nice to add the test that showed the failure to connect prior to the fix and verify that it passes now. But we can add that later. Thank you for your contribution.

You're welcome. Actually the test module is so big and a bit complicated. I will try to add the test case and make sure everything else is as it should be.

**Comment by kozlovic** [comment]
@biot2 I meant that maintainers could add the test, you don't have to especially if you are new to the project. I have added the test myself, you can see PR #697

**Pull request merged**
