### PR TITLE
[FIXED] Remove calls to "ERR_remove_thread_state()" which was depreca…

### PR DESCRIPTION
**Pull request by danesh-d**
…ted in OpenSSL 1.1.0

The thread initialisation and deinitialisation is done automatically in
OpenSSL from version 1.1.0.

### CODE REVIEW

**Comment by danesh-d** [comment]
This patch addresses the issue #226.

**Comment by kozlovic** [comment]
@danesh-d Thanks for the contribution! However, I would like the change to take into account the version of OpenSSL. As you can see from the travis build result, since an older OpenSSL library is used, this causes memory leaks:
```
131/176 MemCheck: #131: Test_SSLBasic ...........................   Defects: 6
132/176 MemCheck: #132: Test_SSLVerify ..........................   Defects: 6
133/176 MemCheck: #133: Test_SSLVerifyHostname ..................   Defects: 6
134/176 MemCheck: #134: Test_SSLSkipServerVerification ..........   Defects: 6
135/176 MemCheck: #135: Test_SSLCiphers .........................   Defects: 8
136/176 MemCheck: #136: Test_SSLMultithreads ....................   Defects: 8
137/176 MemCheck: #137: Test_SSLConnectVerboseOption ............   Defects: 6
```

**Comment by danesh-d** [comment]
@kozlovic Sure. I will re-submit updated version of this patch.

**Comment by danesh-d** [comment]
@kozlovic The code uses deprecated function only for older versions of OpenSSL, otherwise the function is not called. I also added unit test for the function that compares OpenSSL version. Tests are also passed.

**Comment by kozlovic** [comment]
@danesh-d Thank you for the contribution! I tested and it works on Windows too.

**Pull request merged**
