### PR TITLE
Release v3.7.0

### PR DESCRIPTION
**Pull request by levb**
- [x] merge dev into main https://github.com/nats-io/nats.c/pull/664
- [x] version updated to `3.7.0`, `-beta` removed
- [x] `NATS_VERSION_REQUIRED_NUMBER` set to `030700` since public structs changed
- [x] Docs regenerated
- [x] Release PR posted (this)
- [x] Update the doc branch gh-pages
- [x] Release notes
- [ ] [Tag and release on github](https://github.com/nats-io/nats-internal/blob/master/release-instructions/GO.md#create-release-tag)
- [ ] [NATS Site Update](https://github.com/nats-io/nats-internal/blob/master/release-instructions/GO.md#create-release-tag)
- [ ] Publish to brew
- [ ] Update `main` and `dev` with next version, `"-beta"`

See [Release instructions](https://github.com/nats-io/nats-internal/blob/master/release-instructions/C.md)

### CODE REVIEW

**Comment by kozlovic** [comment]
@levb I would have waited for dev to be merged into main before doing this PR. Should be equivalent since you have based it from the other branch, but you understand that this PR ultimately needs to be done against main (and more importantly merged into main), which right now would not be the case. So once you merge #664, either edit this PR to select `main` as the base branch, and hopefully, everything else is ok, or recreate this PR based out of main.

**Comment by levb** [comment]
@kozlovic yes, I created this in anticipation of merging #664->main first. Added a "Do not merge" label to clarify the intention (and yes, it'd just target `main` after 664 is merged.

**Review by Jarema — APPROVED** [review]
LGTM!

**Comment by levb** [comment]
@Jarema @mtmk I ran into issues with the brew step, posted in Slack. Maybe one of you could run the formula update, with better success? The steps are [here](https://github.com/nats-io/nats-internal/blob/master/release-instructions/C.md#brew)

**Comment by levb** [comment]
Worked for @Jarema , thx for the help.

**Comment by mtmk** [comment]
> Worked for @Jarema , thx for the help.

my brew is still upgrading, it's been a while... 🤣

**Pull request merged**
