### PR TITLE
[FIXED] Add a marginal to buffers to silent truncated buffer warnings

### PR DESCRIPTION
**Pull request by danesh-d**

### CODE REVIEW

**Comment by danesh-d** [comment]
This patch addressed issue #231.

**Comment by kozlovic** [comment]
@danesh-d Not sure about this fix. Clearly, the two tests could be easily fixed by just copying directly in errProto and if needed make the stack buffer bigger without the need for the constant you use.

What are the warnings you are referring to and how did you get it to print them? I just checked the code and all places where I use the connection's errTxt buffer, I do use `snprintf()`, which as far as I know, will ensure that I do not overflow the buffer and makes sure that a terminating `\0` is added.

**Comment by danesh-d** [comment]
Sure you know better how this can be fixed. I am sorry that I missed to update the commit message. I have two lines to suppress warnings given by gcc but then I realized that clang is also used so decided to remove those #pragma directives to avoid making thins overcomplicated.

**Comment by rigtorp** [comment]
> What are the warnings you are referring to and how did you get it to print them?
@kozlovic Check my PR #225. These are new warnings added to recent GCC and clang versions.

**Comment by kozlovic** [comment]
@danesh-d Should be fixed with #239 and prior.

**Pull request closed without merging**
